name: sm_tv
description: SM TV - Live TV & Sports Streaming App
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  firebase_core: ^2.25.0
  firebase_database: ^10.4.0
  firebase_auth: ^4.17.0
  google_mobile_ads: ^5.0.0
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.1.4
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
